### ISSUE TITLE
106 bugged

### ISSUE THREAD

**Issue by c00lunderscorekit** [Clockwork-Interactive/Secure-Craft-Protect#2]
106 can't be hit, blown up,  or move, he can however float
he can send you into his dimension and kill mobs 
teleportation dosent seem to be affected 
altso his dimension is kinda odd

**Comment by c00lunderscorekit** [comment]
https://medal.tv/games/minecraft/clips/i6iTYwOYksZSnPiSN/d1337vh3hFhk?invite=cr-MSxkeXAsMTg1OTM3OTIxLA
for some proof

**Comment by YesMan20** [comment]
106 is by default, immune to any damage, not sure what you meant by the 2nd thing.

**Comment by c00lunderscorekit** [comment]
then that isnt a bug but he dosent move on his own

**Comment by c00lunderscorekit** [comment]
he can teleport and send you into his dimension but he cant move or hit you

**Comment by YesMan20** [comment]
He cant hit you because he sends you to his dimension upon touching you

**Comment by c00lunderscorekit** [comment]
he cant hit me cus he cant move

**Comment by c00lunderscorekit** [comment]
and cus i dont go next to him
